import type { Listing, Passport, Seller } from "./types";

// Unsplash source helper — themed campus / product photography
const img = (id: string, w = 800, h = 800) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format`;

export const sellers: Seller[] = [
  { id: "u1", name: "Aarav Mehta", course: "CSE", year: "3rd Year", avatar: "AM", rating: 4.9 },
  { id: "u2", name: "Riya Sharma", course: "ECE", year: "2nd Year", avatar: "RS", rating: 4.8 },
  { id: "u3", name: "Rahul Nair", course: "Mechanical", year: "4th Year", avatar: "RN", rating: 4.7 },
  { id: "u4", name: "Ananya Rao", course: "Design", year: "1st Year", avatar: "AR", rating: 5.0 },
  { id: "u5", name: "Kabir Singh", course: "Civil", year: "3rd Year", avatar: "KS", rating: 4.6 },
];

export const seedListings: Listing[] = [
  {
    id: "CL-2026-0001",
    name: "Nike Windrunner Jacket",
    description:
      "Bought online, wrong size and can't be returned. Worn once. Great for the monsoon season on campus.",
    category: "Clothing",
    price: 3000,
    operation: "SELL",
    condition: "Like New",
    location: "Hostel Block A",
    image: img("1551028719-00167b16eac5"),
    seller: sellers[0],
    circularScore: 96,
    createdAt: "2026-09-14",
    status: "LISTED",
  },
  {
    id: "CL-2026-0002",
    name: "Engineering Mathematics (Kreyszig)",
    description: "Advanced Engineering Mathematics, 10th ed. Clean pages, no highlights. Perfect for 2nd year.",
    category: "Books",
    price: 450,
    operation: "SELL",
    condition: "Good",
    location: "Library",
    image: img("1544716278-ca5e3f4abd8c"),
    seller: sellers[1],
    circularScore: 88,
    createdAt: "2026-09-13",
    status: "LISTED",
  },
  {
    id: "CL-2026-0003",
    name: "Casio FX-991EX Calculator",
    description: "Scientific calculator, fully working. Selling as I graduated. Exchange for a lab coat also welcome.",
    category: "Electronics",
    price: 700,
    operation: "EXCHANGE",
    condition: "Good",
    location: "Academic Block",
    image: img("1587145820266-a5951ee6f620"),
    seller: sellers[2],
    circularScore: 82,
    createdAt: "2026-09-12",
    status: "LISTED",
  },
  {
    id: "CL-2026-0004",
    name: "Hostel Study Chair (needs repair)",
    description: "Wooden chair, one loose leg. Solid frame — perfect repair or upcycle project.",
    category: "Furniture",
    price: 0,
    operation: "DONATE",
    condition: "Damaged",
    location: "Hostel Block C",
    image: img("1503602642458-232111445657"),
    seller: sellers[3],
    circularScore: 74,
    createdAt: "2026-09-11",
    status: "LISTED",
  },
  {
    id: "CL-2026-0005",
    name: "Hero Sprint Cycle",
    description: "Reliable single-speed cycle. Well maintained, new tyres last month. Great for the daily class commute.",
    category: "Sports",
    price: 4200,
    operation: "SELL",
    condition: "Good",
    location: "Hostel Block B",
    image: img("1485965120184-e220f721d03e"),
    seller: sellers[4],
    circularScore: 90,
    createdAt: "2026-09-10",
    status: "LISTED",
  },
  {
    id: "CL-2026-0006",
    name: "USB-C Fast Charger (faulty cable)",
    description: "Adapter works perfectly, cable frays. Good for parts recovery or a quick repair.",
    category: "Electronics",
    price: 0,
    operation: "DONATE",
    condition: "Fair",
    location: "Repair Center",
    image: img("1583863788434-e58a36330cf6"),
    seller: sellers[0],
    circularScore: 61,
    createdAt: "2026-09-09",
    status: "LISTED",
  },
  {
    id: "CL-2026-0007",
    name: "Wildcraft 35L Backpack",
    description: "Durable laptop backpack, all zips working. Minor fading. Perfect for treks and daily use.",
    category: "Clothing",
    price: 900,
    operation: "SELL",
    condition: "Good",
    location: "Cafeteria",
    image: img("1553062407-98eeb64c6a62"),
    seller: sellers[1],
    circularScore: 85,
    createdAt: "2026-09-08",
    status: "LISTED",
  },
  {
    id: "CL-2026-0008",
    name: "Adjustable LED Desk Lamp",
    description: "Warm/cool modes, USB powered. Barely used from my hostel desk. Exchange for a table fan?",
    category: "Electronics",
    price: 550,
    operation: "EXCHANGE",
    condition: "Like New",
    location: "Hostel Block A",
    image: img("1507003211169-0a1dd7228f2d"),
    seller: sellers[2],
    circularScore: 87,
    createdAt: "2026-09-07",
    status: "LISTED",
  },
  {
    id: "CL-2026-0009",
    name: "Yonex Badminton Racket",
    description: "Lightweight racket, freshly restrung. Selling my spare. Great for beginners and the sports club.",
    category: "Sports",
    price: 1100,
    operation: "SELL",
    condition: "Like New",
    location: "Academic Block",
    image: img("1626224583764-f87db24ac4ea"),
    seller: sellers[3],
    circularScore: 89,
    createdAt: "2026-09-06",
    status: "LISTED",
  },
  {
    id: "CL-2026-0010",
    name: "Cardboard Moving Boxes (x8)",
    description: "Sturdy boxes from my hostel move. Free to a good home — reuse for storage or recycle.",
    category: "Packaging",
    price: 0,
    operation: "DONATE",
    condition: "Fair",
    location: "Hostel Block B",
    image: img("1607166452427-7e4477079cb9"),
    seller: sellers[4],
    circularScore: 68,
    createdAt: "2026-09-05",
    status: "LISTED",
  },
];

export const seedPassport: Passport = {
  id: "CL-2026-0001",
  itemName: "Nike Windrunner Jacket",
  image: img("1551028719-00167b16eac5"),
  events: [
    { stage: "LISTED", label: "Listed on Reloop marketplace", date: "14 Sep 2026", done: true },
    { stage: "INTERESTED", label: "3 students expressed interest", date: "14 Sep 2026", done: true },
    { stage: "SOLD", label: "Sold to Riya Sharma · ₹3,000", date: "15 Sep 2026", done: true },
    { stage: "TRANSFERRED", label: "Handover at Hostel Block A", date: "15 Sep 2026", done: true },
    { stage: "REPAIRED", label: "Minor button repair logged", date: "—", done: false },
    { stage: "RECYCLED", label: "End-of-life recovery (future)", date: "—", done: false },
  ],
};

export const campusPoints = [
  { id: "p1", type: "listing", label: "Nike Jacket", x: 34, y: 28 },
  { id: "p2", type: "listing", label: "Study Chair", x: 62, y: 40 },
  { id: "p3", type: "listing", label: "Hero Cycle", x: 48, y: 66 },
  { id: "p4", type: "repair", label: "Repair Center", x: 74, y: 58 },
  { id: "p5", type: "recycle", label: "Recycling Point", x: 20, y: 72 },
  { id: "p6", type: "donate", label: "Donation Booth", x: 55, y: 20 },
  { id: "p7", type: "listing", label: "Desk Lamp", x: 82, y: 32 },
] as const;
